[tool.poetry]
name = "petprojectbyflask"
version = "1.0.0"
description = ""
authors = ["VoblaSuperFish <author@mail>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

